name: Run PlayTests

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Target Host'
        required: true
        default: 'https://ffxivvenues.com'
        type: string

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        working-directory: FFXIVVenues.PlayTests
        run: dotnet build
      - name: Ensure browsers are installed
        working-directory: FFXIVVenues.PlayTests
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - run: echo "HOST=${{ inputs.host }}" >> $GITHUB_ENV
        shell: bash
      - name: Run tests
        working-directory: FFXIVVenues.PlayTests
        run: dotnet test
